modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/DynamicTreesTeam/DynamicTrees-AlexsMobs/issues"

[[mods]]
modId = "dtalexsmobs"
version = "${file.jarVersion}"
displayName = "Dynamic Trees for Alex's Mobs"

updateJSONURL = "https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/AlexsMobs.json?raw=true"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-alexs-mobs"

authors="Max Hyper" #optional
description='''
Compatibility Mod between Dynamic trees and Alex's Mobs
'''

[[dependencies.dtalexsmobs]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dtalexsmobs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.dtalexsmobs]]
modId = "dynamictrees"
mandatory = true
versionRange = "[1.3.0-BETA10,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dtalexsmobs]]
modId = "dynamictreesplus"
mandatory = false
versionRange = "[1.2.0-BETA2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dtalexsmobs]]
modId = "alexsmobs"
mandatory = true
versionRange = "[1.22.0,)"
ordering = "AFTER"
side = "BOTH"